/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import java.util.regex.Pattern;

/**
 *
 * @author Admin
 */
public class FindFriend extends javax.swing.JInternalFrame {

    /**
     * Creates new form NhapUserForm
     */
    public FindFriend() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstFriend = new javax.swing.JList<>();
        txtFriendName = new javax.swing.JTextField();
        btnFindFriend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddFriend = new javax.swing.JButton();
        txtSelectFriend = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tìm Bạn Bè");

        lstFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFriendMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstFriend);

        txtFriendName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFriendNameKeyPressed(evt);
            }
        });

        btnFindFriend.setText("Tìm");
        btnFindFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFriendActionPerformed(evt);
            }
        });

        jLabel1.setText("NickName");

        btnAddFriend.setText("Kết Bạn");
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        txtSelectFriend.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtFriendName, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSelectFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddFriend))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtFriendName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelectFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFriendActionPerformed
       String msg = "findFriend///"+Login.client.NickName+"///"+txtFriendName.getText()+"///"+"SERVER";
       Login.client.send(msg); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindFriendActionPerformed

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
       String msg = "addFriend///"+Login.client.NickName+"///"+txtSelectFriend.getText()+"///"+"SERVER";
       Login.client.send(msg); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFriendActionPerformed

    private void lstFriendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFriendMouseClicked
        txtSelectFriend.setText(this.lstFriend.getSelectedValue());
        // TODO add your handling code here:
    }//GEN-LAST:event_lstFriendMouseClicked

    private void txtFriendNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFriendNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnFindFriend.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtFriendNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnFindFriend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<String> lstFriend;
    private javax.swing.JTextField txtFriendName;
    private javax.swing.JTextField txtSelectFriend;
    // End of variables declaration//GEN-END:variables
}
